version: "24.0.6"
services:
  discovery:
    container_name: discovery
    build: ./EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=recette
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  plat:
    container_name: plat
    build: ./plat
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082:8082"
    image: "plat"
    depends_on:
      - discovery

  theme:
    container_name: theme
    build: ./Theme
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8088:8088"
    image: "theme"
    depends_on:
      - discovery

  profile:
    build: ./profile-service
    environment:
    - SPRING_APPLICATION_NAME=profile-service
    - SERVER_PORT=8089
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/profile?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=
    - SPRING_JPA_OPEN-IN-VIEW=false
    - SPRING_JPA_SHOW-SQL=true
    - SPRING_JPA_HIBERNATE_DDL-AUTO=update  

    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
    ports:
    - 8089:8089
    image: "profile"
    depends_on:
    - discovery
    - mysql

  recette:
    build: ./ms_gestionRecette
    environment:
      - SPRING_APPLICATION_NAME=ms_gestionRecette
      - SERVER_PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/recette?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_OPEN-IN-VIEW=false
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
    ports:
      - "8086:8086"
    image: "recette"
    depends_on:
      - discovery
      - mysql

  MsCommande:
    build: ./MsCommande
    environment:
      - SPRING_APPLICATION_NAME=ingredient-service
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mscommande?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_OPEN-IN-VIEW=false
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
    ports:
      - "8087:8087"
    image: "mscommande"
    depends_on:
      - discovery
      - mysql

  events:
    build: ./events1
    environment:
      - SPRING_APPLICATION_NAME=Event-s
      - SERVER_PORT=8089
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alabenhmida?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_OPEN-IN-VIEW=false
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
    ports:
      - "8091:8091"
    image: "events"
    depends_on:
      - discovery
      - mysql
      
  nodeapp:
    container_name: auth # Name your Node.js container
    image: node:14 # Use an official Node.js image from Docker Hub
    working_dir: /auth
    volumes:
      - .:/auth # Mount the current directory to /app in the container
    ports:
      - "3000:3000" # Map port 3000 in the container to port 3000 on the host
    command: npm start

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
    image: "gateway"
    depends_on:
      - discovery 
    
